### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by burdged** [foss2serve/Corral#1]
Readme.md refers to the template-README.md which should be README-template.md

**Comment by StoneyJackson** [comment]
Very good. I flipped this when I moved from GitLab. In GitLab, it picks up the first file it finds that starts with README and displays it as the project's readme. And since - comes before . in lexicographical ordering, GitLab would display README-template.md instead of README.md. Way more than you wanted to hear. But I thought it was interesting, if a little annoying :)

Anyway... all fixed :)

**Comment by burdged** [comment]
☺ Knowledge is power!

Prof. Darci L. Burdge
MAT/CSC/ITE Department
Nassau Community College
Garden City, NY 11530
(516)572-7383 ext. 26826
